# Generated by Django 4.1.3 on 2022-12-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
