# Generated by Django 4.1.4 on 2022-12-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name_plural': 'Income'},
        ),
    ]
